# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  php-tests-72:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      # Specify the version you desire here
      - image: cimg/php:7.2

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps: &php-test-steps
      - run:
          name: Install PCov
          command: |
            pecl install pcov && docker-php-ext-enable pcov
      - checkout

      # - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      # - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Composer Install
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit
      - run:
          name: PHPUnit
          command: |
              php --define pcov.enabled=1 \
                ./vendor/bin/phpunit ./tests \
                --log-junit ./.coverage/php-tests-junit.xml \
                --coverage-clover ./.coverage/php-tests-coverage.xml
      - store_test_results:
          path: ./.coverage
      - codecov/upload:
          file: ./.coverage/php-tests-coverage.xml
  php-tests-74:
    docker:
      # Specify the version you desire here
      - image: cimg/php:7.4
    steps: *php-test-steps
workflows:
  version: 2
  commit:
    jobs:
      - php-tests-74
      - php-tests-72
