# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  php-tests-8:
    docker:
      - image: cimg/php:8.0
    steps: &php-test-steps
      # Dependency needed for generating coverage.
      - run:
          name: Install PCov
          command: |
            sudo pecl install pcov
      # Checkout the repo.
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit
      - run:
          name: Run Tests
          command: composer tests:ci
      - store_test_results:
          path: ./.coverage
      - codecov/upload:
          file: ./.coverage/php-tests-coverage.xml
workflows:
  version: 2
  commit:
    jobs:
      - php-tests-8
